# Generated by Django 3.0.6 on 2020-05-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_t2'),
    ]

    operations = [
        migrations.CreateModel(
            name='t3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('pic', models.ImageField(blank='true', null='true', upload_to='profiles')),
            ],
        ),
    ]
