# Generated by Django 3.0.6 on 2020-05-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200518_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t3',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
