# Generated by Django 3.0.6 on 2020-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_t3_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3',
            name='mul',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
