# Generated by Django 3.0.6 on 2020-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_t3_mul'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
