# Generated by Django 3.0.6 on 2020-05-21 05:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_t3_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Pic', models.ImageField(blank='true', null='true', upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('flattype', models.CharField(max_length=20)),
                ('furnishing', models.CharField(max_length=20)),
                ('aminities', models.CharField(max_length=100)),
                ('avlfrom', models.DateTimeField(blank=True, null=True)),
                ('avlupto', models.DateTimeField(blank=True, null=True)),
                ('avlgen', models.CharField(max_length=20)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
    ]
