# Generated by Django 3.0.6 on 2020-05-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='city',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
