# Generated by Django 3.0.6 on 2020-05-21 07:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_owner_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='mo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None),
        ),
    ]
