# Generated by Django 3.0.6 on 2020-05-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20200521_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='mo',
            field=models.CharField(max_length=10),
        ),
    ]
