# Generated by Django 3.0.6 on 2020-05-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20200521_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='mo',
        ),
    ]
