# Generated by Django 3.0.6 on 2020-05-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_remove_owner_mo'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='mo',
            field=models.CharField(default=8460250047, max_length=10),
            preserve_default=False,
        ),
    ]
