# Generated by Django 3.0.6 on 2020-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20200521_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
