# Generated by Django 3.0.6 on 2020-05-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_owner_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
    ]
