# Generated by Django 3.0.6 on 2020-05-31 03:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomshare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=200)),
                ('lgender', models.CharField(max_length=10)),
                ('interest', models.CharField(max_length=150)),
                ('avlfrom', models.DateTimeField(blank=True, null=True)),
                ('avlupto', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('aminities', models.CharField(max_length=100)),
                ('Pic', models.ImageField(blank='true', null='true', upload_to='')),
                ('city', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
                ('furnishing', models.CharField(max_length=20)),
                ('hometype', models.CharField(max_length=20)),
                ('bath', models.CharField(max_length=20)),
                ('parking', models.CharField(max_length=20)),
            ],
        ),
    ]
