# Generated by Django 3.0.6 on 2020-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_roomshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomshare',
            name='Pic',
            field=models.FileField(blank='true', null='true', upload_to=''),
        ),
    ]
